### ISSUE TITLE
Parsing recipe after fail

### ISSUE THREAD

**Issue by muratozk** [voloviq/meta-licheepinano#1]
Hello @voloviq . I had the opportunity to try the lichee nano image again. This time I ran into a different problem.. What can I do ? Do you have a suggestion? I test it other meta's etc console-image qt5-image meta-toolchain-qt5. 

`Loading cache: 100% |#######################################################################################################################################################################| Time: 0:00:01
Loaded 3293 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'virtual/bootloader'
u-boot PROVIDES virtual/bootloader but was skipped: PREFERRED_PROVIDER_virtual/bootloader set to u-boot-custom, not u-boot
u-boot-suniv-spiflash PROVIDES virtual/bootloader but was skipped: PREFERRED_PROVIDER_virtual/bootloader set to u-boot-custom, not u-boot-suniv-spiflash
u-boot-suniv PROVIDES virtual/bootloader but was skipped: PREFERRED_PROVIDER_virtual/bootloader set to u-boot-custom, not u-boot-suniv
ERROR: Required build target 'qt5-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['qt5-image', 'virtual/bootloader']`

https://pastebin.ubuntu.com/p/4jY56GCBHG/

**Comment by voloviq** [comment]
Please make git pull. I corrected some recipes.

**Comment by muratozk** [comment]
Thank you so much. Try it bitbake qt5-image successfully working.
Is compiled. One more question.. 

1) ts_calibrate run after result. Not calibrate.
`[   60.404733] i2c i2c-0: mv64xxx: I2C bus locked, block: 1
[   60.410095] input input0: Poll touch data failed: -110
[   62.564735] i2c i2c-0: mv64xxx: I2C bus locked, block: 1
[   62.570101] input input0: Poll touch data failed: -110
`

2) How to using ethernet. I have a JP1081B No:9700 otg ethernet device. Not started. How to configuration ?
3) How to change other lcd screen using. 480x272 resolution ?
4) How can we cross-compile with qt to this device and throw the software we made ?

I'm sorry i asked so many questions. I'm new to Yocto.

**Comment by voloviq** [comment]
Regarding to i2c and touchscreen please refer to 

https://github.com/voloviq/meta-licheepinano/issues/2

For this MPU I'm not sure if We can handle QT5, I kept qt5-image and it's compile well, but this unit have only 32MB DDR. For this MPU I recommend light framework. Try to google something. OTG is not tested probably something needs to be add in defconfig and in dts. Can You provide me Your display model, in free time I can check where to change it. In u-boot just remove one of the patch and should be working with 480x272.

**Comment by muratozk** [comment]
I tested the screen
https://cdn.ozdisan.com/ETicaret_Dosya/571861_161376.pdf

**Comment by voloviq** [comment]
Dropped activity with LCD.
